### ISSUE TITLE
Problem Opening main.py

### ISSUE THREAD

**Issue by Error404Hacked** [FlamingFury00/Stardust-Bot#2]
Hi, Im having issue to open main.py when I double click it just closes it self.  Do I have to install anything else? because I dont get it.

**Comment by FlamingFury00** [comment]
Hello, this repository is related to [RLBot](http://www.rlbot.org/), a framework for running *offline* Rocket League bots. You can try Stardust by downloading RLBotGUI, then:
- Download this repository
- Open RlBotGUI
- Click "Add" top-left
- Click "Load Folder" and select the repository folder.

*Remember that this is only for **offline** games, inside the RLBot enviroment and you can't use it for ranked.*
